services:
    postgresql:
        container_name: postgresql-servidor
        image: postgres:15.4-bullseye
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER= ${POSTGRES_USER}
            - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
            - POSTGRES_DB= ${POSTGRES_DB}
            - PGDATA= ${PGDATA}
        volumes:
            # es buena practica path relativo desde el proyecto ./_data:/var/lib/postgresql
            - ./_data:/var/lib/postgresql/data
        restart: always
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports: 
            - "80:80"
        depends_on: 
            - postgresql