services:
    postgresql:
        container_name: postgresql-servidor
        image: postgres:15.4-bullseye
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=proyecto
            - POSTGRES_PASSWORD=river
            - POSTGRES_DB=proyecto
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            # es buena practica path relativo desde el proyecto ./_data:/var/lib/postgresql
            - ./_data:/var/lib/postgresql/data
        restart: always
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "proyecto@proyecto.com"
            PGADMIN_DEFAULT_PASSWORD: "river"
        ports: 
            - "80:80"
        depends_on: 
            - postgresql